name: Trailer Tracker

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  spy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Track trailers
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
          DOMAIN_URL: ${{ secrets.DOMAIN_URL }}
        if: env.SECRET_TOKEN != null
        run: |
          sh .github/workflows/spy-scripts/undercover-bookie.sh
